name: μΏ λ§ ν¨ν‚¤μ§€ iOS17μ—μ„ ν…μ¤νΈν•κΈ°

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/μΏ λ§') && contains(github.event.comment.body, 'ios17 ν¨ν‚¤μ§€ ν…μ¤νΈ')
    runs-on: macos-13  #μµμ‹ λ²„μ „
    steps:
      # ν…μ¤νΈ μ”μ²­ μ‹μ‘
      - name: Test iOS17
        run: |
          echo "iOS17 μ—μ„ ν¨ν‚¤μ§€μ λ¨λ“  ν…μ¤νΈ νƒ€κ²μ„ ν…μ¤νΈ ν•©λ‹λ‹¤."
         
      # iOS17 ν…μ¤νΈ μ‘λ‹µ μ»¤λ©νΈ
      - name: Add Test comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'π”¨ iOS 17 iPhone 15 Pro μ—μ„ μΏ λ§ ν¨ν‚¤μ§€λ¥Ό ν…μ¤νΈ ν•©λ‹λ‹¤.'
            })

      # μ½”λ“λ¥Ό μ²΄ν¬μ•„μ›ƒ ν•©λ‹λ‹¤.
      - name: Checkout repository
        uses: actions/checkout@v2
    
      # Xcode λ²„μ „μ„ μ„¤μ •ν•©λ‹λ‹¤.
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
    
      # NoticeFeaturesTests μ¤ν‚΄μ„ ν…μ¤νΈν•©λ‹λ‹¤.
      - name: NoticeFeaturesTests ν…μ¤νΈ
        run: |
          cd KuringPackage
          xcodebuild test -scheme NoticeFeaturesTests -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' -skipMacroValidation
          
      # SubscriptionFeaturesTests μ¤ν‚΄μ„ ν…μ¤νΈν•©λ‹λ‹¤.
      - name: SubscriptionFeaturesTests ν…μ¤νΈ
        run: |
          cd KuringPackage
          xcodebuild test -scheme SubscriptionFeaturesTests -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' -skipMacroValidation
      
      # ν…μ¤νΈ μ„±κ³µμ‹ μ»¤λ©νΈ
      - name: Add Build comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'β… iOS17 μ—μ„ ν¨ν‚¤μ§€λ¥Ό μ„±κ³µμ μΌλ΅ ν…μ¤νΈ ν–μµλ‹λ‹¤.'
            })

      # ν…μ¤νΈ μ‹¤ν¨μ‹ μ»¤λ©νΈ
      - name: Notify failure
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'π“¬ iOS17 μ—μ„ ν¨ν‚¤μ§€ ν…μ¤νΈμ— μ‹¤ν¨ν–μµλ‹λ‹¤. Actionsμ—μ„ μ‹¤ν¨ κ²°κ³Όλ¥Ό ν™•μΈν•΄μ£Όμ„Έμ”.'
            })
        if: failure()
